import { Roboto, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/common/Navbar";
import Footer from "@/components/ui/common/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // choose what you need
});

export const metadata = {
  title: "KAVAS Wholesale Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${roboto.variable} ${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer/>
        </body>
    </html>
  );
}
