export const productsData = {
  electronics: [
    {
      id: 1,
      name: "Wireless Earbuds TWS Pro",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 599,
      minQty: 50,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1585386959984-a41552231658",
    },
    {
      id: 2,
      name: "Noise Cancelling Headphones",
      category: "electronics",
      subcategory: "audio & headphones",
      price: 1499,
      minQty: 20,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1518444065439-e933c06ce9cd",
    },
    {
      id: 3,
      name: "Laptop Cooling Pad",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 399,
      minQty: 30,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1587202372775-989c1b1a7b4c",
    },
    {
      id: 4,
      name: "USB-C Hub 7 in 1",
      category: "electronics",
      subcategory: "laptops & computers",
      price: 899,
      minQty: 25,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1587206668289-c21d4c2c92e4",
    },
    {
      id: 5,
      name: "CCTV Camera 1080p",
      category: "electronics",
      subcategory: "cameras & security",
      price: 1299,
      minQty: 10,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1581091870627-3a6c8c9f7f47",
    },
    {
      id: 6,
      name: "LED Monitor 24 inch",
      category: "electronics",
      subcategory: "monitors",
      price: 7999,
      minQty: 5,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
    },
    {
      id: 7,
      name: "Mechanical Keyboard RGB",
      category: "electronics",
      subcategory: "keyboards & mice",
      price: 1999,
      minQty: 15,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    },
    {
      id: 8,
      name: "Power Bank 20000mAh",
      category: "electronics",
      subcategory: "power & batteries",
      price: 899,
      minQty: 40,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1580910051074-3eb694886505",
    },
  ],

  apparel: [
    {
      id: 9,
      name: "Men Cotton T-Shirts Pack",
      category: "apparel",
      subcategory: "men wear",
      price: 299,
      minQty: 100,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
    },
    {
      id: 10,
      name: "Women Casual Kurti",
      category: "apparel",
      subcategory: "women wear",
      price: 499,
      minQty: 80,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03",
    },
    {
      id: 11,
      name: "Kids Printed Dress",
      category: "apparel",
      subcategory: "kids wear",
      price: 399,
      minQty: 60,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b",
    },
    {
      id: 12,
      name: "Denim Jeans Bulk",
      category: "apparel",
      subcategory: "men wear",
      price: 899,
      minQty: 70,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
    },
  ],

  hardware: [
    {
      id: 13,
      name: "Electric Drill Machine",
      category: "hardware",
      subcategory: "tools",
      price: 2499,
      minQty: 10,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789",
    },
    {
      id: 14,
      name: "Complete Tool Kit Set",
      category: "hardware",
      subcategory: "tools",
      price: 1499,
      minQty: 15,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1581141849291-1125c7b692b5",
    },
  ],

  fmcg: [
    {
      id: 15,
      name: "Herbal Bath Soap Pack",
      category: "fmcg",
      subcategory: "personal care",
      price: 120,
      minQty: 200,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1600180758890-6b94519a8ba6",
    },
    {
      id: 16,
      name: "Shampoo Sachets Bulk",
      category: "fmcg",
      subcategory: "personal care",
      price: 2,
      minQty: 1000,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1585238342028-4f6f7c4f5b0f",
    },
  ],

  furniture: [
    {
      id: 17,
      name: "Office Chair Ergonomic",
      category: "furniture",
      subcategory: "office",
      price: 4999,
      minQty: 5,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    },
    {
      id: 18,
      name: "Wooden Study Table",
      category: "furniture",
      subcategory: "home",
      price: 6999,
      minQty: 3,
      supplier: "Trusted Supplier",
      image: "https://images.unsplash.com/photo-1598300056393-4aac492f4344",
    },
  ],

  automotive: [
    {
      id: 19,
      name: "Car Seat Cover Set",
      category: "automotive",
      subcategory: "spare parts",
      price: 1999,
      minQty: 20,
      supplier: "Gold Supplier",
      image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2",
    },
  ],

  packaging: [
    {
      id: 20,
      name: "Corrugated Boxes Bulk",
      category: "packaging",
      subcategory: "boxes",
      price: 30,
      minQty: 500,
      supplier: "Verified Supplier",
      image: "https://images.unsplash.com/photo-1586769852044-692d6e3703f0",
    },
  ],
};
